#!/usr/bin/env node
// Switch the Convex CLI between deployments by rewriting .env.local.
//
//   node scripts/switch-env.mjs cloud|self|local   (or: npm run use:cloud|use:self|use:local)
//
// Reads .env.<target> (cloud -> .env.cloud, self -> .env.selfhosted,
// local -> .env.localdev), replaces ONLY the Convex-owned keys in .env.local
// and keeps every other line (app secrets like PI_API_KEY stay put).
// The previous .env.local is saved as .env.local.bak.
//
// The CLI targets cloud when CONVEX_DEPLOYMENT is set and self-hosted when
// CONVEX_SELF_HOSTED_URL is set. Having both is ambiguous, so this refuses.
import { readFileSync, writeFileSync, existsSync, copyFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const FILES = { cloud: ".env.cloud", self: ".env.selfhosted", local: ".env.localdev" };
// Keys this script owns. Anything else in .env.local is preserved untouched.
const CONVEX_KEYS = [
  "CONVEX_DEPLOYMENT",
  "CONVEX_SELF_HOSTED_URL",
  "CONVEX_SELF_HOSTED_ADMIN_KEY",
  "CONVEX_URL",
  "CONVEX_SITE_URL",
];

const target = process.argv[2];
if (!FILES[target]) {
  console.error(`Usage: node scripts/switch-env.mjs <${Object.keys(FILES).join("|")}>`);
  process.exit(1);
}

const sourcePath = resolve(ROOT, FILES[target]);
if (!existsSync(sourcePath)) {
  console.error(`Missing ${FILES[target]}. Copy ${FILES[target]}.example and fill it in.`);
  process.exit(1);
}

const keyOf = (line) => (line.match(/^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=/) || [])[1];
const read = (p) => (existsSync(p) ? readFileSync(p, "utf8").split(/\r?\n/) : []);

const incoming = read(sourcePath).filter((l) => l.trim() !== "");
const incomingKeys = new Set(incoming.map(keyOf).filter(Boolean));

// Guard: the source file itself must not mix the two targeting modes.
if (incomingKeys.has("CONVEX_DEPLOYMENT") && incomingKeys.has("CONVEX_SELF_HOSTED_URL")) {
  console.error(
    `${FILES[target]} sets both CONVEX_DEPLOYMENT and CONVEX_SELF_HOSTED_URL.\n` +
      `The Convex CLI cannot target cloud and self-hosted at once — remove one.`,
  );
  process.exit(1);
}

const localPath = resolve(ROOT, ".env.local");
const kept = read(localPath).filter((line) => {
  const k = keyOf(line);
  // Drop Convex-owned keys and anything the new file redefines; keep the rest
  // (comments, blank lines and app secrets survive the switch).
  return !(k && (CONVEX_KEYS.includes(k) || incomingKeys.has(k)));
});

if (existsSync(localPath)) copyFileSync(localPath, resolve(ROOT, ".env.local.bak"));

const header = `# Generated by scripts/switch-env.mjs — target: ${target} (${FILES[target]})`;
const body = [header, ...incoming, "", ...kept].join("\n").replace(/\n{3,}/g, "\n\n").trimEnd();
writeFileSync(localPath, body + "\n");

const deployment = (incoming.find((l) => keyOf(l) === "CONVEX_DEPLOYMENT") || "").split("=")[1] ?? "";
const mode = incomingKeys.has("CONVEX_SELF_HOSTED_URL")
  ? "self-hosted"
  : deployment.trim().startsWith("local:")
    ? "CLI local deployment"
    : "Convex Cloud";
console.log(`.env.local now targets: ${target} (${mode})`);
console.log(`  kept ${kept.filter(keyOf).length} non-Convex key(s); backup at .env.local.bak`);
if (mode === "Convex Cloud" || mode === "self-hosted") {
  console.log(`  reminder: 'npx convex dev' pushes on every save — use 'npx convex deploy' here.`);
}
